# -*- coding: utf-8 -*-
"""
Created on Tue Aug 20 10:27:17 2024

@author: shender
"""

initial_ratings_e = {'BOR': 700,'CTB': 300,'DHR': 200,'KEM': 450,'MRD': 900,'MRD(B)': 200,'PAN': 250,'TIL': 600,'TNF': 700,'TNF(B)': 200,'SWS': 350,}
initial_ratings_w = {'DGC': 1000,'SLG': 1200,'SDA': 650,'MCM': 900,'CRD': 450,'DIS': 450,'PSO': 350,'CWB': 425,'RCR': 425,'PIT': 300,'CBB': 400,'PHH': 250,'AUA': 200,'TOM': 300,'CAB': 300,'FLC': 100,'CHK': 250,'DEM': 80,'TRD': 50,'CLG': 50,'PIT(B)': 20,'CBB(B)': 40,'SDA(B)': 120,'SLG(B)': 180,'CAB(B)': 40,'CRD(B)': 100,'PHH(B)': 150}

team_names = {
    'AUA': 'Austin Anarchy',
    'CWB': 'Carolina Wreckingballs',
    'CAB': 'Casco Bay Roller Derby',
    'CAB(B)': 'Casco Bay (B)',
    'CBB': 'Chicago Bruise Brothers',
    'CBB(B)': 'Chicago (B)',
    'CHK': 'Chinook City Roller Derby',
    'CLG': 'Cleveland Guardian\'s Roller Derby',
    'DGC': 'Denver Ground Control',
    'DEM': 'Detroit Men\'s Roller Derby',
    'DIS': 'Disorder',
    'FLC': 'Flour City Roller Derby',
    'CRD': 'Concussion Roller Derby',
    'CRD(B)': 'Concussion Roller Derby (B)',
    'MCM': 'Magic City Misfits',
    'PHH': 'Philadelphia Hooligans',
    'PHH(B)': 'Philadelphia Shenanigans (B)',
    'PIT': 'Pittsburgh Roller Derby',
    'PIT(B)': 'Pittsburgh ZomBees (B)',
    'PSO': 'Puget Sound Outcast Derby',
    'RCR': 'Race City Rebels',
    'SDA': 'San Diego Aftershocks',
    'SDA(B)': 'San Diego Tremors (B)',
    'SLG': 'St. Louis Gatekeepers',
    'SLG(B)': 'St. Louis B-Keepers (B)',
    'TRD': 'Terminus Roller Derby',
    'TOM': 'Toronto Men\'s Roller Derby',
    'BOR': 'Borderland Bandits Roller Derby',
    'CTB': 'Crash Test Brummies',
    'DHR': 'DHR Men\'s Roller Derby',
    'KEM': 'Kent Men\'s Roller Derby',
    'MRD': 'Manchester Roller Derby',
    'MRD(B)': 'Manchester (B)',
    'PAN': 'Panam Squad',
    'TIL': 'The Inhuman League',
    'TNF': 'Tyne and Fear Roller Derby',
    'TNF(B)': 'Tyne and Fear (B)',
    'SWS': 'South Wales Silures',
}

gamecount_active = {
    'AUA': 0,
    'CWB': 0,
    'CAB': 0,
    'CAB(B)': 0,
    'CBB': 0,
    'CBB(B)': 0,
    'CHK': 0,
    'CLG': 0,
    'DGC': 0,
    'DEM': 0,
    'DIS': 0,
    'FLC': 0,
    'CRD': 0,
    'CRD(B)': 0,
    'MCM': 0,
    'PHH': 0,
    'PHH(B)': 0,
    'PIT': 0,
    'PIT(B)': 0,
    'PSO': 0,
    'RCR': 0,
    'SDA': 0,
    'SDA(B)': 0,
    'SLG': 0,
    'SLG(B)': 0,
    'TRD': 0,
    'TOM': 0,
    'BOR': 0,
    'CTB': 0,
    'DHR': 0,
    'KEM': 0,
    'MRD': 0,
    'MRD(B)': 0,
    'PAN': 0,
    'TIL': 0,
    'TNF': 0,
    'TNF(B)': 0,
    'SWS': 0,
}
